# Generated by Django 5.2 on 2025-11-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='times_added_to_cart',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
